version: "3"

services:
  flask:
    container_name: form-checker_container
    build: .
    environment:
      MONGO_URL: mongodb://mongo
      PORT: 27017
      DB_NAME: forms_db
      COLLECTION_NAME: forms
      HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db/forms.json:/docker-entrypoint-initdb.d/forms.json
    image: mongo
